---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-tekton
resources:
- https://github.com/tektoncd/pipeline/releases/download/v0.29.0/release.yaml
- https://github.com/tektoncd/triggers/releases/download/v0.17.0/release.yaml
- https://github.com/tektoncd/triggers/releases/download/v0.17.0/interceptors.yaml
- https://github.com/tektoncd/dashboard/releases/download/v0.21.0/tekton-dashboard-release.yaml
