apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pgo
resources:
- namespace.yaml
- https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.6.2/installers/kubectl/postgres-operator.yml
