# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
- namespace.yaml
- envoy-gateway.yaml
- gateway.yaml
- httproutes.yaml
- monitors.yaml
