apiVersion: v1
appVersion: 6.1.1
deprecated: true
description: DEPRECATED - A reverse proxy that provides authentication with Google,
  Github or other providers
engine: gotpl
home: https://pusher.github.io/oauth2_proxy/
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
kubeVersion: '>=1.9.0-0'
name: oauth2-proxy
sources:
- https://github.com/pusher/oauth2_proxy
version: 4.0.0
