apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant
resources:
- volumes
- release.yaml
- vernemq.yaml
- zwave2mqtt.yaml
- ../../../../shared/postgres

patchesStrategicMerge:
- postgres.yaml
