# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../config/secrets.yaml
- operators
- repositories
- cert-manager.yaml
- crossplane.yaml
- external-snapshotter.yaml
- hardware.yaml
- k8tz.yaml
- kyverno.yaml
- longhorn.yaml
- metallb.yaml
- reloader.yaml
