---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../config/secrets.yaml
- operators
- repositories
- cert-manager.yaml
- external-snapshotter.yaml
- hardware.yaml
- ingress.yaml
- k8tz.yaml
- kyverno.yaml
- longhorn.yaml
- metallb.yaml
- reloader.yaml
