apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    expose:
      tls:
        certSource: none
      ingress:
        hosts:
          core: r.zro.io
          notary: notary.zro.io
    externalURL: https://r.zro.io
    persistence:
      imageChartStorage:
        disableredirect: true
        type: s3
        s3:
          bucket: registry
          regionendpoint: http://internal.minio.svc
          secure: false
    database:
      type: external
      external:
        host: postgres.registry.svc
        username: postgres
        # password: valuesFrom:Secret:postgres-auth
    redis:
      type: external
      external:
        addr: "redis.registry.svc:6379"
    jobservice:
      jobLogger: database
  valuesFrom:
  - kind: Secret
    name: harbor-values
  - kind: Secret
    name: postgres-auth
    valuesKey: password
    targetPath: database.external.password
