apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system
resources:
- github.com/metallb/metallb/manifests?ref=v0.9.6

configMapGenerator:
- name: config
  files:
  - config=config.yaml

generatorOptions:
  disableNameSuffixHash: true
