---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceph-dashboard
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  rules:
  - host: ceph.zro.io
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 7000
        path: /
        pathType: Prefix

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceph-s3-gateway
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  rules:
  - host: s3.zro.io
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-rgw-object-store
            port:
              number: 80
        path: /
        pathType: Prefix
