apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-system
resources:
- namespace.yaml
- cloudflare-token.yaml
- cert-manager.yaml
- issuer.yaml
- ingress-nginx.yaml
- wildcard-certificate.yaml
