apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./drone-secrets/minio.yaml
- ./drone-secrets/registry.yaml
- ./drone-secrets/sonarqube.yaml
- ./drone/drone.yaml
- ./drone/gitea-credentials.yaml
- ./drone/postgres-auth.yaml
- ./home-assistant/github-credentials.yaml
- ./home-assistant/home-assistant-env.yaml
- ./home-assistant/postgres-auth.yaml
- ./home-assistant/zwave.yaml
- ./ingress-system/cloudflare-token.yaml
- ./longhorn-system/backup-credentials.yaml
- ./media/frigate-values.yaml
- ./media/plex-values.yaml
- ./minio/credentials.yaml
- ./minio/internal-credentials.yaml
- ./neolink/neolink-values.yaml
- ./nextcloud/nextcloud-values.yaml
- ./oauth2-proxy/oauth2-proxy-values.yaml
- ./prometheus-system/prometheus-stack-values.yaml
- ./registry/harbor-values.yaml
