apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://oteemo.github.io/charts
      chart: sonarqube
      version: 9.5.0
      sourceRef:
        kind: HelmRepository
        name: oteemo
        namespace: flux-system
  values:
    image:
      repository: sonarqube
      tag: 8.7.0-community
    service:
      externalPort: 80
    ingress:
      enabled: true
      hosts:
      - name: sonarqube.zro.io
        path: /
    initContainersSecurityContext:
      privileged: false
    postgresql:
      enabled: false
      postgresqlServer: postgres
      postgresqlDatabase: postgres
      postgresqlUsername: postgres
  valuesFrom:
  - kind: Secret
    name: postgres-auth
    valuesKey: password
    targetPath: postgresql.postgresqlPassword
