apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media
resources:
- volumes
# - frigate.yaml
# - nzbget.yaml
# - nzbhydra2.yaml
# - plex.yaml
# - radarr.yaml
# - sonarr.yaml
